
GET http://localhost:3000/api/account HTTP/1.1
content-type: application/json


###

# User register
POST  http://localhost:3000/api/account/register HTTP/1.1
content-type: application/json

{
  "user": {
    "username": "Cihat Baba",
    "name": "Cihat Salik",
    "email": "test1@test.com",
    "password": "test123123!",
    "passwordConfirmation": "test123123!"
  }
}

###

# User login

POST http://localhost:3000/api/account/session HTTP/1.1
content-type: application/json

{
  "email": "testtest234@test.com",
  "password": "test123123!"
}

###

# get one user
DELETE  http://localhost:3000/api/account/#id HTTP/1.1
content-type: application/json

###

# get user
GET http://localhost:3000/api/account/get-all-users HTTP/1.1
content-type: application/json

###
