GET http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

###

POST  http://localhost:3000/api/users/register HTTP/1.1
content-type: application/json

{
  "user": {
    "username": "testtest3",
    "name": "Test Test3",
    "email": "test3@test.com",
    "password": "test123123!",
    "passwordConfirmation": "test123123!"
  }
}

###

GET  http://localhost:3000/api/users/session HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users/session HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "test@test.com",
    "password": "test123123!"
  }
}

###

GET  http://localhost:3000/api/users/session HTTP/1.1
content-type: application/json

###

DELETE  http://localhost:3000/api/users/session HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

###